ktor:
  deployment:
    port: 8080
  application:
    modules:
      - haydende.storefront.ApplicationKt.main
      - haydende.storefront.route.UserRouteKt.userModule
      - haydende.storefront.route.AddressRouteKt.addressModule

database:
  connection-string: jdbc:postgresql://localhost:5432/storefront?user=peegee&password=somepassword
#  driver-class-name: org.postgres.Driver
